target("assignment1_part_a")
set_kind("binary")
add_packages("glad", "glfw")
add_files("$(projectdir)/Assignment1/part_a/*.cpp")
add_includedirs("$(projectdir)/Assignment1/part_a")
set_rundir("$(projectdir)")
target_end()

target("assignment1_part_b")
set_kind("binary")
add_deps("engine")
add_files("$(projectdir)/Assignment1/part_b/*.cpp")
add_includedirs("$(projectdir)/Assignment1/part_b")
set_rundir("$(projectdir)")
target_end()
